package org.mintcode.errabbit.core.report;

import org.bson.types.ObjectId;
import org.mintcode.errabbit.core.analysis.result.AnalysisResultSet;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Set;

/**
 * Report
 * Generated by ReportGenerator
 * Include rabbits' logging level graph data.
 * Created by soleaf on 15. 8. 9..
 */
@Document(collection = "reports")
public class Report implements Serializable{

    private static final DateFormat format = new SimpleDateFormat("yyyy.MM.dd");

    @Id
    private ObjectId id;
    private Date sendTime;
    private Date targetDate;
    private Boolean read = false;
    private AnalysisResultSet logReport;
    private Set<String> targets; // target rabbits ID

    public ObjectId getId() {
        return id;
    }
    public void setId(ObjectId id) {
        this.id = id;
    }

    /**
     * Generated time
     * @return
     */
    public Date getSendTime() {
        return sendTime;
    }
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * Report result
     * @return
     */
    public AnalysisResultSet getLogReport() {
        return logReport;
    }
    public void setLogReport(AnalysisResultSet logReport) {
        this.logReport = logReport;
    }

    /**
     * Read status
     * @return
     */
    public Boolean getRead() {
        return read == null ? false : read;
    }
    public void setRead(Boolean read) {
        this.read = read;
    }

    /**
     * Target rabbits Id set
     * @return
     */
    public Set<String> getTargets() {
        return targets;
    }
    public void setTargets(Set<String> targets) {
        this.targets = targets;
    }

    /**
     * Reporting target date (aggregation condition)
     * @return
     */
    public Date getTargetDate() {
        return targetDate;
    }
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }

    /**
     * Target date time with format
     * for UI
     * @return
     */
    public String getTargetDateWithFormat(){
        return format.format(targetDate);
    }

    /**
     * Get calendar with target date
     * @return
     */
    private Calendar targetDateCal(){
        Calendar cal = Calendar.getInstance();
        cal.setTime(targetDate);
        return cal;
    }

    /**
     * Get targetYear
     * @return
     */
    public Integer getTargetYear(){
        return targetDateCal().get(Calendar.YEAR);
    }

    /**
     * Get targetMonth
     * @return
     */
    public Integer getTargetMonth(){
        return targetDateCal().get(Calendar.MONTH);
    }

    /**
     * Get targetDay
     * @return
     */
    public Integer getTargetDay(){
        return targetDateCal().get(Calendar.DAY_OF_MONTH);
    }

    @Override
    public String toString() {
        return "Report{" +
                "id=" + id +
                ", sendTime=" + sendTime +
                ", targetDate=" + targetDate +
                ", read=" + read +
                ", logReport=" + logReport +
                ", targets=" + targets +
                '}';
    }
}
